# Generated by Django 4.1.3 on 2022-11-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentmethod_account_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='name',
            new_name='purchase_name',
        ),
    ]
