# Generated by Django 4.1.3 on 2022-11-12 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOccurrenceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('modified_start', models.DateTimeField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classoccurrence')),
            ],
            options={
                'verbose_name': 'Override',
                'verbose_name_plural': 'Overrides',
            },
        ),
    ]
