# Generated by Django 4.1.3 on 2022-11-12 01:55

from django.db import migrations
import eventtools.models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classoccurrenceoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoccurrence',
            name='repeat',
            field=eventtools.models.ChoiceTextField(blank=True, choices=[('RRULE:FREQ=DAILY', 'Daily'), ('RRULE:FREQ=WEEKLY', 'Weekly'), ('RRULE:FREQ=WEEKLY;INTERVAL=2', 'Biweekly'), ('RRULE:FREQ=MONTHLY', 'Monthly'), ('RRULE:FREQ=YEARLY', 'Yearly')], default='', verbose_name='repeat'),
        ),
    ]
