# Generated by Django 4.1.3 on 2022-11-13 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_rename_capacity_class_total_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeattendee',
            name='class_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_attendees', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='recurringattendee',
            name='class_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_attendees', to='classes.class'),
        ),
        migrations.CreateModel(
            name='OneTimeNonAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField()),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_non_attendees', to='classes.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
