# Generated by Django 4.1.3 on 2022-11-13 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0006_alter_onetimeattendee_class_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onetimeattendee',
            unique_together={('user', 'class_key', 'class_date')},
        ),
        migrations.AlterUniqueTogether(
            name='onetimenonattendee',
            unique_together={('user', 'class_key', 'class_date')},
        ),
    ]
