# Generated by Django 4.1.3 on 2022-11-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_onetimeattendee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='coach',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
