# Generated by Django 4.1.3 on 2022-11-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studioamenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='studioimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
